### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-create-or-update-text-file.js#15]
**What happened?**

@wolfy1339 reported there was a problem when using this plugin from Node and trying to decode this file: https://github.com/wolfy1339/test-repository/blob/6c46223b6d3464bb5d17773d42ad557524e56d2c/.github/workflows/update-prettier.yml

**What the problem might be**

@wolfy1339 can you add the exact error message you got? YOu mentioned that the code tried to use `atob` although you used it from Node?

**Comment by wolfy1339** [comment]
**Error message**:
```
InvalidCharacterError: Invalid character
    at atob (node:buffer:1243:7)
    at browserBase64ToUtf8 (/home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octokit/plugin-create-or-update-text-file/dist-node/index.js:106:36)
    at getFileContents (/home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octokit/plugin-create-or-update-text-file/dist-node/index.js:174:16)
    at async composeCreateOrUpdateTextFile (/home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octokit/plugin-create-or-update-text-file/dist-node/index.js:203:23)
    at async Object.script (file:///home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/script.js:56:32)
    at async runScriptAgainstRepositories (file:///home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octoherd/cli/lib/run-script-against-repositories.js:64:9)
    at async octoherd (file:///home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octoherd/cli/index.js:114:3)
    at async run (file:///home/wolfy1339/Desktop/Programming/octoherd-fix-prettier-update-workflow/node_modules/@octoherd/cli/bin/run.js:22:5)
```

**System Info:**
```
$ node --version
v16.1.0
```

**Comment by wolfy1339** [comment]
I looked around to see how people detected NodeJS, and found this method, which is in this diff. With the diff applied, `nodeBase64ToUtf8` gets called instead of `browserBase64ToUtf8`
```diff
@@ -8,6 +8,7 @@
//   https://stackoverflow.com/questions/30631927/converting-to-base64-in-javascript-without-deprecated-escape-call

const hasAtob = "atob" in globalThis;
+ const isBrowser = !(globalThis.process?.release?.name || 'not node')

function browserUtf8ToBase64(data: string) {
  return btoa(unescape(encodeURIComponent(data)));
@@ -25,5 +26,5 @@ function nodeBase64ToUtf8(data: string) {
  return Buffer.from(data, "base64").toString("utf-8");
}

- export const utf8ToBase64 = hasAtob ? browserUtf8ToBase64 : nodeUtf8ToBase64;
- export const base64ToUtf8 = hasAtob ? browserBase64ToUtf8 : nodeBase64ToUtf8;
+ export const utf8ToBase64 = isBroswer ? browserUtf8ToBase64 : nodeUtf8ToBase64;
+ export const base64ToUtf8 = isBrowser ? browserBase64ToUtf8 : nodeBase64ToUtf8;
```

**Comment by gr2m** [comment]
I was able to reproduce the problem in the browser.

```js
function browserBase64ToUtf8(data) {
  return decodeURIComponent(escape(atob(data)));
}

function browserUtf8ToBase64(data) {
  return btoa(unescape(encodeURIComponent(data)));
}

// https://docs.github.com/en/rest/reference/repos#get-repository-content
const response = await fetch('https://api.github.com/repos/wolfy1339/test-repository/contents/.github/workflows/update-prettier.yml?ref=6c46223b6d3464bb5d17773d42ad557524e56d2c')
const json = await response.json()
const textContent = browserBase64ToUtf8(json.content)

// throws "Uncaught DOMException: String contains an invalid character"
browserBase64ToUtf8(textContent)
```

So we have two things to fix:

1. Detect Node correctly (in Node 16)
2. Fix the encoding method

Node 16 ships with `atob`/`btoa` which has the same implementation as the browser. The problem with `atob`/`btoa` is that they don't support UTF8, they use unicode. I went down a rabbit whole figuring this out and thought the whole escaping/unescaping will fix the problem (it did with my tests at the time), but looks like it didn't.

I'll have to look into this again

**Comment by gr2m** [comment]
I think the `b64EncodeUnicode` and `b64DecodeUnicode` methods from [this StackOverflow answer](https://stackoverflow.com/a/30106551/206879) is what we need. 

The explanation they give might explain the error being thrown

> (Why do we need to do this? `('00' + c.charCodeAt(0).toString(16)).slice(-2)` prepends a 0 to single character strings, for example when `c == \n`, the `c.charCodeAt(0).toString(16)` returns `a`, forcing `a` to be represented as `0a`).
